name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.0'
          channel: 'stable'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
      - name: Getting Packages
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
      - name: Upload Release Apk
        uses: actions/upload-artifact@v3.0.0
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
